/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LazyGraph (https://sketchfab.com/lazygraph)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/old-bike-8e6d1067635f4c4084c9a48cb0bc228f
title: Old Bike
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-75.57, 66.11, -15.69]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Base_Base_0.geometry} material={materials.Base} />
          </group>
          <group position={[67.88, 211.95, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Handlebar_Handle_0.geometry} material={materials.Handle} />
          </group>
          <group position={[-73.18, 225.96, 0]} rotation={[-Math.PI / 2, -0.1, 0]} scale={[48.16, 48.16, 48.16]}>
            <mesh geometry={nodes.Saddle_Saddle_0.geometry} material={materials.Saddle} />
          </group>
          <group position={[-127.64, 80.26, -0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Wheels_Wheels_0.geometry} material={materials.Wheels} />
          </group>
          <group position={[-92.67, 137.61, -9.35]} rotation={[-Math.PI / 2, -0.95, -1.57]} scale={[1.36, 1.36, 2.39]}>
            <mesh geometry={nodes.Brake_Joint_Brake_0.geometry} material={materials.Joint_Brake} />
          </group>
          <group position={[44.89, 87.24, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Pedals_Details_0.geometry} material={materials.Details} />
          </group>
          <group position={[-82.55, 153.87, -2.33]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Chains_Chains_0.geometry} material={nodes.Chains_Chains_0.material} />
            <mesh geometry={nodes.Chains_Chains_0_1.geometry} material={nodes.Chains_Chains_0_1.material} />
            <mesh geometry={nodes.Chains_Chains_0_2.geometry} material={nodes.Chains_Chains_0_2.material} />
            <mesh geometry={nodes.Chains_Chains_0_3.geometry} material={nodes.Chains_Chains_0_3.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
